package ürün;

import anaEkran.AdminPaneli;
import anaEkran.giriş;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class ürümekranı extends javax.swing.JFrame {

    /**
     * Creates new form ürümler
     */
     DefaultTableModel model;
    ürünişlemler islemler =  new ürünişlemler();
    private Connection con = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet Rs=null;
    public void bağlantı(){
        String url = "jdbc:mysql://" + satıcı.Database.host + ":" + satıcı.Database.port + "/" + satıcı.Database.db_ismi+ "?useUnicode=true&characterEncoding=utf8";
        
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Bulunamadı....");
        }
        
        
        try {
            con = DriverManager.getConnection(url, satıcı.Database.kullanici_adi, satıcı.Database.parola);
            System.out.println("Bağlantı Başarılı...");
            
            
        } catch (SQLException ex) {
            System.out.println("Bağlantı Başarısız...");
            //ex.printStackTrace();
        }
        
        
        
            
          
    }
    
    
    public ürümekranı() {
        initComponents();
        model = (DefaultTableModel) ÜrünTablo.getModel();
        ürünGoruntule();
        Filtreleme();
    }
     public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        ÜrünTablo.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ürünİsim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ÜrünEkle = new javax.swing.JButton();
        ÜrünDüzenle = new javax.swing.JButton();
        ÜrünSil = new javax.swing.JButton();
        ÜrünMiktar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ÜrünTablo = new javax.swing.JTable();
        ÜrümTemizle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ÜrünKategori = new javax.swing.JComboBox<>();
        ÜrünFiyat = new javax.swing.JTextField();
        arama_cubugu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gerituşu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("ÜRÜNLERİN LİSTESİ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("ÜRÜN MİKTAR");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("ÜRÜN İSİM");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("ÜRÜN FİYAT");

        Ürünİsim.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Ürünİsim.setForeground(new java.awt.Color(255, 102, 0));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("KATEGORİ");

        ÜrünEkle.setBackground(new java.awt.Color(255, 102, 0));
        ÜrünEkle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ÜrünEkle.setForeground(new java.awt.Color(255, 255, 255));
        ÜrünEkle.setText("Ekle");
        ÜrünEkle.setBorder(null);
        ÜrünEkle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ÜrünEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÜrünEkleActionPerformed(evt);
            }
        });

        ÜrünDüzenle.setBackground(new java.awt.Color(255, 102, 0));
        ÜrünDüzenle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ÜrünDüzenle.setForeground(new java.awt.Color(255, 255, 255));
        ÜrünDüzenle.setText("Düzenle");
        ÜrünDüzenle.setBorder(null);
        ÜrünDüzenle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ÜrünDüzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÜrünDüzenleActionPerformed(evt);
            }
        });

        ÜrünSil.setBackground(new java.awt.Color(255, 102, 0));
        ÜrünSil.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ÜrünSil.setForeground(new java.awt.Color(255, 255, 255));
        ÜrünSil.setText("Sil");
        ÜrünSil.setBorder(null);
        ÜrünSil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ÜrünSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÜrünSilActionPerformed(evt);
            }
        });

        ÜrünMiktar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ÜrünMiktar.setForeground(new java.awt.Color(255, 102, 0));

        ÜrünTablo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ÜrünTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "İsim", "Miktar", "Fiyat", "Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ÜrünTablo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ÜrünTablo.setRowHeight(25);
        ÜrünTablo.setSelectionBackground(new java.awt.Color(255, 102, 0));
        ÜrünTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ÜrünTabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ÜrünTablo);
        if (ÜrünTablo.getColumnModel().getColumnCount() > 0) {
            ÜrünTablo.getColumnModel().getColumn(0).setResizable(false);
            ÜrünTablo.getColumnModel().getColumn(1).setResizable(false);
            ÜrünTablo.getColumnModel().getColumn(2).setResizable(false);
            ÜrünTablo.getColumnModel().getColumn(3).setResizable(false);
            ÜrünTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        ÜrümTemizle.setBackground(new java.awt.Color(255, 102, 0));
        ÜrümTemizle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ÜrümTemizle.setForeground(new java.awt.Color(255, 255, 255));
        ÜrümTemizle.setText("Temizle");
        ÜrümTemizle.setBorder(null);
        ÜrümTemizle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ÜrümTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÜrümTemizleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("ÜRÜNLERİN YÖNETİMİ");

        ÜrünKategori.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ÜrünKategori.setForeground(new java.awt.Color(255, 102, 0));
        ÜrünKategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ÜrünFiyat.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ÜrünFiyat.setForeground(new java.awt.Color(255, 102, 0));

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ürünİsim)
                    .addComponent(ÜrünKategori, 0, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ÜrünSil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ÜrünMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ÜrünFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ÜrünEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(ÜrünDüzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(ÜrümTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(351, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(298, 298, 298)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Ürünİsim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ÜrünMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ÜrünFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ÜrünKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ÜrümTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ÜrünSil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ÜrünDüzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ÜrünEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel7)
                    .addContainerGap(497, Short.MAX_VALUE)))
        );

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("x");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        gerituşu.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\forward-arrow - Kopya.png")); // NOI18N
        gerituşu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerituşu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerituşuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gerituşu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerituşu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ÜrünTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ÜrünTabloMouseClicked
        // TODO add your handling code here:
        int selectedrow =ÜrünTablo.getSelectedRow();
        
        Ürünİsim.setText(model.getValueAt(selectedrow,1).toString());
        ÜrünMiktar.setText(model.getValueAt(selectedrow,2).toString());
        ÜrünFiyat.setText(model.getValueAt(selectedrow,3).toString());
    }//GEN-LAST:event_ÜrünTabloMouseClicked

    private void ÜrünEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÜrünEkleActionPerformed
        // TODO add your handling code here:
         if((Ürünİsim.getText().isEmpty())||(ÜrünMiktar.getText().isEmpty())||(ÜrünFiyat.getText().isEmpty())){
            
            JOptionPane.showMessageDialog(this,"Kayıt İşlemi Başarısız...");
        
        }else{
        
        
        String ad  =  Ürünİsim.getText();
        int miktar = Integer.valueOf(ÜrünMiktar.getText());
        double fiyat =Double.valueOf(ÜrünFiyat.getText());
        String kategori =ÜrünKategori.getSelectedItem().toString();

        islemler.ürünEkle(ad,miktar,fiyat,kategori);

        ürünGoruntule();

        JOptionPane.showMessageDialog(this,"Yeni Ürün Başarıyla Eklendi...");
        }
    }//GEN-LAST:event_ÜrünEkleActionPerformed

    private void ÜrünDüzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÜrünDüzenleActionPerformed
        // TODO add your handling code here:
        String ad  =  Ürünİsim.getText();
        int miktar = Integer.valueOf(ÜrünMiktar.getText());
        double fiyat =Double.valueOf(ÜrünFiyat.getText());
        

        int selectedrow = ÜrünTablo.getSelectedRow();

        if (selectedrow == -1) {

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Ürün Tablosu şu anda boş. ");
            }
            else {
                JOptionPane.showMessageDialog(this,"Lütfen güncellenecek bir ürün seçin.");
            }
        }
        else {

            int id = (int)model.getValueAt(selectedrow,0);
            String kategori =ÜrünKategori.getSelectedItem().toString();
            islemler.ürünGuncelle(id,ad,miktar,fiyat,kategori);

            ürünGoruntule();

            JOptionPane.showMessageDialog(this,"Ürün başarıyla güncellendi...");
        }
    }//GEN-LAST:event_ÜrünDüzenleActionPerformed

    private void ÜrünSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÜrünSilActionPerformed
        // TODO add your handling code here:
        int selectedrow = ÜrünTablo.getSelectedRow();
        
        if (selectedrow == -1) {
            if (model.getRowCount() == 0 ) {
                JOptionPane.showMessageDialog(this,"Ürün tablosu şu anda boş...");
            }
            else {
                JOptionPane.showMessageDialog(this,"Lütfen silinecek bir ürün seçin...");
            }

        }
        else {
            int id = (int)model.getValueAt(selectedrow,0);

            islemler.ürünSil(id);

            ürünGoruntule();

            JOptionPane.showMessageDialog(this,"Ürün başarıyla silindi...");

        }
    }//GEN-LAST:event_ÜrünSilActionPerformed

    private void ÜrümTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÜrümTemizleActionPerformed
        // TODO add your handling code here:Ürünİsim.setText(model.getValueAt(selectedrow,1).toString());
        Ürünİsim.setText("");
        ÜrünMiktar.setText("");
        ÜrünFiyat.setText("");
    }//GEN-LAST:event_ÜrümTemizleActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void arama_cubuguKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyPressed
        // TODO add your handling code here:
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyPressed

    private void gerituşuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerituşuMouseClicked
        // TODO add your handling code here:
        new giriş().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gerituşuMouseClicked

    /**
     * @param args the command line arguments
     */
    public void Filtreleme(){
     try {
         
            bağlantı();
            statement =  con.createStatement();
            String sorgu =  "Select * From user1.kategori";
            
            ResultSet rs =  statement.executeQuery(sorgu);
            
            while(rs.next()) {
                
                String isim = rs.getString("Kategoriİsim");
                ÜrünKategori.addItem(isim);
                
               
                
                
                
                
            }
            
            
            
            
        } catch (SQLException ex) {
           
            
            
        }   
    }
    public void ürünGoruntule() {
        
        model.setRowCount(0);
        
        ArrayList<ürünbilgi> ürün = new ArrayList<ürünbilgi>();
        
        
        ürün = islemler.ürünleriGetir();
        
        if (ürün != null ) {
            
            for (ürünbilgi calisan : ürün) {
                Object[] eklenecek = {calisan.getId(),calisan.getAd(),calisan.getMiktar(),calisan.getFiyat(),calisan.getKategori()};
                
                model.addRow(eklenecek);
                
                
                
            }
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ürümekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ürümekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ürümekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ürümekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ürümekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JLabel gerituşu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ÜrümTemizle;
    private javax.swing.JButton ÜrünDüzenle;
    private javax.swing.JButton ÜrünEkle;
    private javax.swing.JTextField ÜrünFiyat;
    private javax.swing.JComboBox<String> ÜrünKategori;
    private javax.swing.JTextField ÜrünMiktar;
    private javax.swing.JButton ÜrünSil;
    private javax.swing.JTable ÜrünTablo;
    private javax.swing.JTextField Ürünİsim;
    // End of variables declaration//GEN-END:variables

    

   
}
